---

- name: Create Group
  group:
    name: "{{ pms_group }}"
    system: no
    state: present 
  become: true

- name: Create User
  user:
    name: "{{ pms_user }}"
    group: "{{ pms_group }}"
    state: present
    system: no
    createhome: no
    shell: /bin/false
  become: true

# Install from Repo
- block:
  
    - name: Copy PMS Yum Repo
      copy:
        src: files/plex.repo
        dest: /etc/yum.repos.d/plex.repo
        remote_src: false

    - name: Install PMS
      yum:
        pkg: plexmediaserver
        state: installed
        update_cache: yes
      become: yes

  when: pms_install_from_repo

# Install from downloaded RPM
- name: Install from URL
  yum: 
    name: "{{ pms_link }}"
    state: present
    update_cache: yes
    validate_certs: false
  become: yes
  when: not pms_install_from_repo

# Restore
- block:

    - name: Get files from backup_target
      find:
        paths: "{{ pms_backup_target }}"
        patterns: '.*-\d\d\.tar\.gz' # Skips any ${filename}-Metadata.tar.gz files
        use_regex: true
      register: found_files

    - name: Get latest backup file
      set_fact:
        __pms_restore_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first  }}"

    - name: Set Fact for restore_file
      set_fact:
        pms_restore_file: "{{ __pms_restore_file.path }}"
        pms_restore_file_basename: "{{ __pms_restore_file.path|basename|splitext|first|splitext|first }}"

    - name: Restore Backup --> Extract archive
      unarchive:
        src: "{{ item }}"
        dest: /
        remote_src: yes
      become: yes
      with_items:
        - "{{ pms_restore_file }}" # Standard Configuration Backup
        - "{{ pms_backup_target }}/{{ pms_restore_file_basename}}-Metadata.tar.gz" # Metadata Backup

  when: pms_restore_from_backups

# Restore from File
- name: Restore Backup --> Extract archive
  unarchive:
    src: "{{ pms_restore_file }}"
    dest: /
    copy: no
  become: yes
  when:
  - not pms_restore_from_backups
  - pms_restore_file is defined and pms_restore_file|default("") != ""

- name: Enable service
  service: 
    name: plexmediaserver
    enabled: yes
    state: reloaded
  become: true
