---
# Firewall Ports: https://support.plex.tv/hc/en-us/articles/201543147-What-network-ports-do-I-need-to-allow-through-my-firewall-

- name: Check if installed
  command: yum list installed plexmediaserver
  args:
    warn: false
  register: check_installed
  failed_when: check_installed.rc > 1
  changed_when: check_installed.rc > 1

- name: CentOS Install
  include: "install.yml"
  notify: start plex
  when:
    - ansible_distribution == 'CentOS'
    - check_installed.rc == 1

- name: Configure PMS Backups
  include: "backups.yml"
  when: pms_backups_enabled

- name: Update PMS
  yum:
    pkg: plexmediaserver
    update_cache: yes
    state: latest
  become: true
  notify: restart plex
  when:
  - pms_allow_updates
  - check_installed.rc == 0
